- name: Playbook to setup RHCSA exam machines
  hosts: server0.example.com
  tasks:
  - name: Changing password for user root
    user:
      name: root
      password: "{{ 'something' | password_hash('sha512') }}"
  - name: Removing student user from wheel group
    user:
      name: student
      groups: null
      shell: /sbin/nologin
#  - name: Change target to multiuser target
#    service:
#      name: systemd
#      enabled:  true
#      runlevel: 3
  - name: Remove repository
    file:
      path: /etc/yum.repos.d/rhel_dvd.repo
      state: absent
  - name: Disable Selinux
    selinux:
      state: disabled
  - name: Create all partitions
    parted:
      device: /dev/vdb
      state: present
      part_type: primary
      number: "{{ item.name }}"
      label: "{{ item.label }}"
      flags: "{{ item.flag }}"
      part_start: "{{ item.start }}"
      part_end: "{{ item.end }}"
    with_items:
      - { name: '1', label: 'msdos', flag: 'lvm', start: '0MiB', end: '1GiB' }
      - { name: '2', label: 'msdos', flag: 'lvm', start: '1024MiB', end: '2GiB' }
      - { name: '3', label: 'msdos', flag: 'lvm', start: '2049MiB', end: '3GiB' }
  - name: Create volume group vgroup
    lvg:
      vg: vgroup
      pvs: /dev/vdb2
  - name: Create logical volume m7_storage
    lvol:
      pvs: /dev/vdb2
      vg: vgroup
      lv: m7_storage
      size: 700m
  - name: Format all partitions
    filesystem:
      dev: "{{ item.dev }}"
      fstype: "{{ item.fs }}"
    with_items:
      - { dev: '/dev/vdb1', fs: 'ext3' }
      - { dev: '/dev/vgroup/m7_storage', fs: ext4}
  - name:  Create swap space for 3rd partition
    shell:
      cmd: "/usr/sbin/mkswap /dev/vdb3"
  - name: Add swap partition to fstab file.
    lineinfile:
      path: /etc/fstab
      line: "/dev/vdb3 swap swap defaults 0 0"
  - name: mount all partitions
    mount:
      state: mounted
      src: "{{ item[0] }}"
      path: "{{ item[1] }}"
      fstype: "{{ item[2] }}"
    with_nested:
      - [ '/dev/vdb1', '/dev/vgroup/m7_storage' ]
      - [ '/mnt/sroot', '/mnt/lvm' ]
      - [ 'ext3', 'ext4' ]
