- name: Installing packages required for secure nfs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - sssd
    - krb5-workstation
  ignore_errors: true
- name: Installing desktop packages for postfix 
  yum:
    name: mutt 
    state: latest
  when: "'server' in inventory_hostname"
  ignore_errors: true
- name: Installing server packages for postfix
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dovecot
    - postfix
    - httpd
  when: "'desktop' in inventory_hostname"
  ignore_errors: true
- name: Create users on both machines
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
  with_items:
    - { name: tom, uid: 7000 }
    - { name: harry, uid: 8000 }
- name: Changing password for user root
  user:
    name: root
    password: "{{ 'something' | password_hash('sha512') }}"
- name: Remove repository
  file:
    path: /etc/yum.repos.d/rhel_dvd.repo
    state: absent
- name: Disable Selinux
  selinux:
    state: permissive
